package org.arnoldc

import java.io.File

/**
 * JVM Bytecode Executor
 * "DO IT NOW" - Executes compiled .class files
 *
 * This object loads and runs JVM bytecode generated by the ArnoldGenerator.
 * Used when the -run flag is specified to immediately execute the compiled program.
 */
object Executor {

  def execute(className: String) = {
    val classLoader = new java.net.URLClassLoader(
      Array(new File(".").toURI.toURL),
      getClass.getClassLoader
    )
    val clazz = classLoader.loadClass(className)
    // Use getDeclaredConstructor().newInstance() instead of deprecated newInstance()
    val instance = clazz.getDeclaredConstructor().newInstance().asInstanceOf[{def main(test: Array[String])}]
    instance.main(null)
  }
}
